insert into course ( ID,NAME,created_date,last_updated_date) 
values(10001, 'LEARN SPRING',now(),now());


insert into course ( ID,NAME,created_date,last_updated_date)  
values(10002, 'LEARN REACT',now(),now());


insert into course ( ID,NAME,created_date,last_updated_date)  
values(10003, 'LEARN DEEP LEARNING',now(),now());


insert into course ( ID,NAME,created_date,last_updated_date) 
values(10004, 'LEARN NLP',now(),now());


insert into course ( ID,NAME,created_date,last_updated_date) 
values(10005, 'LEARN COMPUTER VISION',now(),now());

INSERT INTO PASSPORT(ID,NUMBER) VALUES(30001,'IN23C364F74');
INSERT INTO PASSPORT(ID,NUMBER) VALUES(30002,'DE234234F74');
INSERT INTO PASSPORT(ID,NUMBER) VALUES(30003,'US23467B2F74');

INSERT INTO STUDENT(ID,NAME,PASSPORT_ID) VALUES(20001,'HARSHIT KASHYAP',30001);
INSERT INTO STUDENT(ID,NAME,PASSPORT_ID) VALUES(20002,'ANJANEYA MISHRA',30002);
INSERT INTO STUDENT(ID,NAME,PASSPORT_ID) VALUES(20003,'NAGU BHAI',30003);




INSERT INTO REVIEW(ID,RATING,DESCRIPTION) VALUES(40001,'5','GREAT COURSE');
INSERT INTO REVIEW(ID,RATING,DESCRIPTION) VALUES(40002,'4','USEFUL COURSE');
INSERT INTO REVIEW(ID,RATING,DESCRIPTION) VALUES(40003,'3','AVERAGE COURSE');
INSERT INTO REVIEW(ID,RATING,DESCRIPTION) VALUES(40004,'2','NOT A GOOD COURSE');
INSERT INTO REVIEW(ID,RATING,DESCRIPTION) VALUES(40005,'1','USELESS COURSE');
INSERT INTO REVIEW(ID,RATING,DESCRIPTION) VALUES(40006,'5','GREAT COURSE');